language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- '7.4'
- 'nightly'
jobs:
  allow_failures:
    - php: 'nightly'
before_script:
- composer require --dev phpunit/phpunit $PHPUNIT_VERSION
- composer require --dev phpunit/php-code-coverage
- phpenv config-rm xdebug.ini
script:
- ./vendor/bin/phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd ..
- mkdir packages
- zip -r packages/tpl_gle.zip tpl_gle/src -x \*.git\*
- git clone -b 1.0.0 https://github.com/Gileba/plg_system_templatecompanion.git plg_system_templatecompanion
- cd plg_system_templatecompanion/src; zip -r ../../packages/plg_system_templatecompanion.zip * -x \*.git\* *.gitignore*; cd ../../
- cp tpl_gle/pkg_gle.xml pkg_gle.xml
- zip pkg_gle packages/tpl_gle.zip packages/plg_system_templatecompanion.zip pkg_ttp.xml
deploy:
  provider: releases
  file:
  - packages/tpl_gle.zip
  - pkg_ttp.zip
  skip_cleanup: true
  on:
    tags: true
  api_key: $GITHUB_TOKEN
after_deploy: curl -T tpl_ttp/tpl_gle.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
